<template>
    <div>
        <content-top>
            <el-button class="add-btn el-icon-plus" type="primary"  @click="addRestaurant">
                添加餐厅
            </el-button>
        </content-top>
        <el-table
                :data="restaurantList"
                style="width: 100%">
            <el-table-column
                    prop="country"
                    label="国家"
                    width="130">
            </el-table-column>
            <el-table-column
                    prop="city"
                    label="城市"
                    width="130">
            </el-table-column>
            <el-table-column
                    prop="type"
                    label="类型">
            </el-table-column>
            <el-table-column
                    prop="name"
                    label="名称"
                    width="130">
            </el-table-column>
            <el-table-column
                    prop="address"
                    label="地址"
                    width="200">
            </el-table-column>
            <el-table-column
                    prop="head"
                    label="人头费">
            </el-table-column>
            <el-table-column
                    prop="commission"
                    label="返佣比例">
            </el-table-column>
            <el-table-column
                    prop="people"
                    label="联系人">
            </el-table-column>
            <el-table-column
                    prop="phone"
                    label="联系电话">
            </el-table-column>
            <el-table-column
                    label="操作">
            </el-table-column>
        </el-table>
    </div>
</template>
<style>

</style>
<script>
    import ContentTop from "src/views/components/ContentTop.vue"
    export default{
        data(){
            return{
                restaurantList:[
                    
                ]
            }
        },
         methods:{
            addRestaurant(){
                this.$router.push({name:"ADD RESTAURANT"})
            }
        },
        components:{
            ContentTop
        }
    }
</script>
